# Default settings for C++
compilers=&clang-enzyme-main
tools=clangquerydefault:strings:ldd

tools.clangquerydefault.exe=/usr/bin/clang-query
tools.clangquerydefault.name=clang-query (default)
tools.clangquerydefault.type=independent
tools.clangquerydefault.class=clang-query-tool
tools.clangquerydefault.stdinHint=Query commands

tools.ldd.name=ldd
tools.ldd.exe=/usr/bin/ldd
tools.ldd.type=postcompilation
tools.ldd.class=readelf-tool
tools.ldd.exclude=djggp
tools.ldd.stdinHint=disabled

tools.strings.exe=/usr/bin/strings
tools.strings.name=strings
tools.strings.type=postcompilation
tools.strings.class=strings-tool
tools.strings.exclude=djggp
tools.strings.stdinHint=disabled

defaultCompiler=clang15-enzyme-main
postProcess=
demangler=c++filt
demanglerType=cpp
objdumper=objdump
options=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*|_dl_relocate_static_pie)$
needsMulti=false
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

#################################
#################################
# Installed libs (See c++.amazon.properties for a scheme of libs group)
libs=eigen:boost:nlohmann_json:petsc

libs.boost.name=Boost
libs.boost.versions=178
libs.boost.url=https://www.boost.org
libs.boost.versions.178.version=1.78.0
libs.boost.versions.178.path=/opt/compiler-explorer/libs/boost_1_78_0

libs.eigen.name=Eigen
libs.eigen.versions=340
libs.eigen.url=http://eigen.tuxfamily.org/index.php?title=Main_Page
libs.eigen.versions.340.version=3.4.0
libs.eigen.versions.340.path=/opt/compiler-explorer/libs/eigen/v3.4.0

libs.nlohmann_json.name=nlohmann::json
libs.nlohmann_json.versions=3111
libs.nlohmann_json.url=https://github.com/nlohmann/json
libs.nlohmann_json.versions.3111.version=3.11.1
libs.nlohmann_json.versions.3111.path=/opt/compiler-explorer/libs/nlohmann_json/v3.11.1/single_include

libs.petsc.name=PETSc
libs.petsc.versions=3194
libs.petsc.url=https://petsc.org
libs.petsc.versions.3194.version=3.19.4
libs.petsc.versions.3194.path=/opt/compiler-explorer/libs/petsc-3.19.4/include

group.clang-enzyme-main.compilers=clang15-enzyme-main:clang16-enzyme-main:clang17-enzyme-main:clang18-enzyme-main:clang19-enzyme-main:clang20-enzyme-main:clang21-enzyme-main:clang22-enzyme-main
group.clang-enzyme-main.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang-enzyme-main.compilerType=clang
group.clang-enzyme-main.supportsExecute=true
group.clang-enzyme-main.isSemVer=true
group.clang-enzyme-main.groupName=CLANG + ENZYME (main)
group.clang-enzyme-main.options=-fno-discard-value-names

compiler.clang15-enzyme-main.exe=/opt/compiler-explorer/clang-15.0.0/bin/clang++
compiler.clang15-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-15.so
compiler.clang15-enzyme-main.semver=15.0.0
compiler.clang15-enzyme-main.name=clang 15 (4658ed0)
compiler.clang16-enzyme-main.exe=/opt/compiler-explorer/clang-16.0.0/bin/clang++
compiler.clang16-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-16.so
compiler.clang16-enzyme-main.semver=16.0.0
compiler.clang16-enzyme-main.name=clang 16 (4658ed0)
compiler.clang17-enzyme-main.exe=/opt/compiler-explorer/clang-17.0.1/bin/clang++
compiler.clang17-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-17.so
compiler.clang17-enzyme-main.semver=17.0.1
compiler.clang17-enzyme-main.name=clang 17 (4658ed0)
compiler.clang18-enzyme-main.exe=/opt/compiler-explorer/clang-18.1.0/bin/clang++
compiler.clang18-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-18.so
compiler.clang18-enzyme-main.semver=18.1.0
compiler.clang18-enzyme-main.name=clang 18 (4658ed0)
compiler.clang19-enzyme-main.exe=/opt/compiler-explorer/clang-19.1.0/bin/clang++
compiler.clang19-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-19.so
compiler.clang19-enzyme-main.semver=19.1.0
compiler.clang20-enzyme-main.exe=/opt/compiler-explorer/clang-20.1.0/bin/clang++
compiler.clang20-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-20.so
compiler.clang20-enzyme-main.semver=20.1.0
compiler.clang21-enzyme-main.exe=/opt/compiler-explorer/clang-21.1.0/bin/clang++
compiler.clang21-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-21.so
compiler.clang21-enzyme-main.semver=21.1.0
compiler.clang22-enzyme-main.exe=/opt/compiler-explorer/clang-assertions-trunk/bin/clang++
compiler.clang22-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-22.so
compiler.clang22-enzyme-main.semver=assertions-trunk
compiler.cuclang15-enzyme-main.semver=15.0.0
compiler.cuclang16-enzyme-main.semver=16.0.0
compiler.cuclang17-enzyme-main.semver=17.0.1
compiler.cuclang18-enzyme-main.semver=18.1.0
compiler.cuclang19-enzyme-main.semver=19.1.0
compiler.cuclang20-enzyme-main.semver=20.1.0
compiler.cuclang21-enzyme-main.semver=21.1.0
compiler.cuclang22-enzyme-main.semver=assertions-trunk
