# Default settings for C
compilers=&clang-enzyme-main
defaultCompiler=cclang12-enzyme-main
demangler=c++filt
objdumper=objdump
postProcess=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

group.clang-enzyme-main.compilers=cclang15-enzyme-main:cclang16-enzyme-main:cclang17-enzyme-main:cclang18-enzyme-main:cclang19-enzyme-main:cclang20-enzyme-main:cclang21-enzyme-main:cclang22-enzyme-main
group.clang-enzyme-main.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang-enzyme-main.compilerType=clang
group.clang-enzyme-main.supportsExecute=true
group.clang-enzyme-main.isSemVer=true
group.clang-enzyme-main.groupName=CLANG + ENZYME (main)
group.clang-enzyme-main.options=-fno-discard-value-names

libs=petsc

libs.petsc.name=PETSc
libs.petsc.versions=3194
libs.petsc.url=https://petsc.org
libs.petsc.versions.3194.version=3.19.4
libs.petsc.versions.3194.path=/opt/compiler-explorer/libs/petsc-3.19.4/include

compiler.cclang15-enzyme-main.exe=/opt/compiler-explorer/clang-15.0.0/bin/clang
compiler.cclang15-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-15.so
compiler.cclang15-enzyme-main.semver=15.0.0
compiler.cclang15-enzyme-main.name=clang 15 (4658ed0)
compiler.cclang16-enzyme-main.exe=/opt/compiler-explorer/clang-16.0.0/bin/clang
compiler.cclang16-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-16.so
compiler.cclang16-enzyme-main.semver=16.0.0
compiler.cclang16-enzyme-main.name=clang 16 (4658ed0)
compiler.cclang17-enzyme-main.exe=/opt/compiler-explorer/clang-17.0.1/bin/clang
compiler.cclang17-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-17.so
compiler.cclang17-enzyme-main.semver=17.0.1
compiler.cclang17-enzyme-main.name=clang 17 (4658ed0)
compiler.cclang18-enzyme-main.exe=/opt/compiler-explorer/clang-18.1.0/bin/clang
compiler.cclang18-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-18.so
compiler.cclang18-enzyme-main.semver=18.1.0
compiler.cclang18-enzyme-main.name=clang 18 (4658ed0)

compiler.cclang19-enzyme-main.exe=/opt/compiler-explorer/clang-19.1.0/bin/clang
compiler.cclang19-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-19.so
compiler.cclang19-enzyme-main.semver=19.1.0
compiler.cclang20-enzyme-main.exe=/opt/compiler-explorer/clang-20.1.0/bin/clang
compiler.cclang20-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-20.so
compiler.cclang20-enzyme-main.semver=20.1.0
compiler.cclang21-enzyme-main.exe=/opt/compiler-explorer/clang-21.1.0/bin/clang
compiler.cclang21-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-21.so
compiler.cclang21-enzyme-main.semver=21.1.0
compiler.cclang22-enzyme-main.exe=/opt/compiler-explorer/clang-assertions-trunk/bin/clang
compiler.cclang22-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-22.so
compiler.cclang22-enzyme-main.semver=assertions-trunk
