compilers=&cuclang-enzyme-main
defaultCompiler=cuclang16-enzyme-main
supportsBinary=true
supportsExecute=false
demangler=c++filt

group.cuclang-enzyme-main.compilers=cuclang15-enzyme-main:cuclang16-enzyme-main:cuclang17-enzyme-main:cuclang18-enzyme-main
group.cuclang-enzyme-main.compilerType=clang-cuda
group.cuclang-enzyme-main.objdumper=/opt/compiler-explorer/cuda/12.1.0/bin/nvdisasm
group.cuclang-enzyme-main.isSemVer=true
group.cuclang-enzyme-main.groupName=CUCLANG + ENZYME (main)
group.cuclang-enzyme-main.options=--cuda-path=/opt/compiler-explorer/cuda/12.1.0 --cuda-gpu-arch=sm_70 --cuda-device-only

compiler.cuclang15-enzyme-main.exe=/opt/compiler-explorer/clang-15.0.0/bin/clang++
compiler.cuclang15-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-15.so 
compiler.cuclang15-enzyme-main.semver=15.0.0
compiler.cuclang15-enzyme-main.name=cuclang 15 (4658ed0)
compiler.cuclang16-enzyme-main.exe=/opt/compiler-explorer/clang-16.0.0/bin/clang++
compiler.cuclang16-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-16.so --cuda-path=/opt/compiler-explorer/cuda/12.1.0 --cuda-gpu-arch=sm_70 --cuda-device-only
compiler.cuclang16-enzyme-main.semver=16.0.0
compiler.cuclang16-enzyme-main.name=cuclang 16 (4658ed0)
compiler.cuclang17-enzyme-main.exe=/opt/compiler-explorer/clang-17.0.1/bin/clang++
compiler.cuclang17-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-17.so --cuda-path=/opt/compiler-explorer/cuda/12.1.0 --cuda-gpu-arch=sm_70 --cuda-device-only
compiler.cuclang17-enzyme-main.semver=17.0.1
compiler.cuclang17-enzyme-main.name=cuclang 17 (4658ed0)
compiler.cuclang18-enzyme-main.exe=/opt/compiler-explorer/clang-18.1.0/bin/clang++
compiler.cuclang18-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-18.so --cuda-path=/opt/compiler-explorer/cuda/12.1.0 --cuda-gpu-arch=sm_70 --cuda-device-only
compiler.cuclang18-enzyme-main.semver=18.0.0
compiler.cuclang18-enzyme-main.name=cuclang 18 (4658ed0)
