binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|(_GLOBAL__sub_I_|\.plt).*|.*@plt(-0x[0-9a-f]+)?)$
objdumper=objdump
demangler=c++filt

compilers=&clang-enzyme-main:&opt-enzyme-main
defaultCompiler=opt12-enzyme-main

group.opt-enzyme-main.compilers=opt15-enzyme-main:opt16-enzyme-main:opt17-enzyme-main:opt18-enzyme-main
group.opt-enzyme-main.compilerType=opt
group.opt-enzyme-main.supportsExecute=false
group.opt-enzyme-main.isSemVer=true
group.opt-enzyme-main.groupName=OPT + ENZYME (main)

compiler.opt15-enzyme-main.exe=/opt/compiler-explorer/clang-15.0.0/bin/opt
compiler.opt15-enzyme-main.options=-load-pass-plugin=/opt/compiler-explorer/main/LLVMEnzyme-15.so -load=/opt/compiler-explorer/main/LLVMEnzyme-15.so --enzyme-attributor=0 -enzyme
compiler.opt15-enzyme-main.semver=15.0.0
compiler.opt15-enzyme-main.name=opt 15 (4658ed0)
compiler.opt16-enzyme-main.exe=/opt/compiler-explorer/clang-16.0.0/bin/opt
compiler.opt16-enzyme-main.options=-load-pass-plugin=/opt/compiler-explorer/main/LLVMEnzyme-16.so -load=/opt/compiler-explorer/main/LLVMEnzyme-16.so --enzyme-attributor=0 -passes=enzyme
compiler.opt16-enzyme-main.semver=16.0.0
compiler.opt16-enzyme-main.name=opt 16 (4658ed0)
compiler.opt17-enzyme-main.exe=/opt/compiler-explorer/clang-17.0.1/bin/opt
compiler.opt17-enzyme-main.options=-load-pass-plugin=/opt/compiler-explorer/main/LLVMEnzyme-17.so -load=/opt/compiler-explorer/main/LLVMEnzyme-17.so --enzyme-attributor=0 -passes=enzyme
compiler.opt17-enzyme-main.semver=17.0.1
compiler.opt17-enzyme-main.name=opt 17 (4658ed0)
compiler.opt18-enzyme-main.exe=/opt/compiler-explorer/clang-18.1.0/bin/opt
compiler.opt18-enzyme-main.options=-load-pass-plugin=/opt/compiler-explorer/main/LLVMEnzyme-18.so -load=/opt/compiler-explorer/main/LLVMEnzyme-18.so --enzyme-attributor=0 -passes=enzyme
compiler.opt18-enzyme-main.semver=18.1.0
compiler.opt18-enzyme-main.name=opt 18 (4658ed0)

group.clang-enzyme-main.compilers=irclang15-enzyme-main:irclang16-enzyme-main:irclang17-enzyme-main:irclang18-enzyme-main
group.clang-enzyme-main.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang-enzyme-main.compilerType=clang
group.clang-enzyme-main.supportsExecute=true
group.clang-enzyme-main.isSemVer=true
group.clang-enzyme-main.groupName=CLANG + ENZYME (main)
group.clang-enzyme-main.options=-fno-discard-value-names

compiler.irclang15-enzyme-main.exe=/opt/compiler-explorer/clang-15.0.0/bin/clang
compiler.irclang15-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-15.so
compiler.irclang15-enzyme-main.semver=15.0.0
compiler.irclang15-enzyme-main.name=clang 15 (4658ed0)
compiler.irclang16-enzyme-main.exe=/opt/compiler-explorer/clang-16.0.0/bin/clang
compiler.irclang16-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-16.so
compiler.irclang16-enzyme-main.semver=16.0.0
compiler.irclang16-enzyme-main.name=clang 16 (4658ed0)
compiler.irclang17-enzyme-main.exe=/opt/compiler-explorer/clang-17.0.1/bin/clang
compiler.irclang17-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-17.so
compiler.irclang17-enzyme-main.semver=17.0.1
compiler.irclang17-enzyme-main.name=clang 17 (4658ed0)

compiler.irclang18-enzyme-main.exe=/opt/compiler-explorer/clang-18.1.0/bin/clang
compiler.irclang18-enzyme-main.options=-fplugin=/opt/compiler-explorer/main/ClangEnzyme-18.so
compiler.irclang18-enzyme-main.semver=18.1.0
compiler.irclang18-enzyme-main.name=clang 18 (4658ed0)
