compilers=&enzyme-opt-main
defaultCompiler=enzyme-opttrunk-main
compilerType=mlir

supportsBinary=false
supportsExecute=false
supportsAsmDocs=false

group.enzyme-opt-main.compilers=enzyme-opttrunk-main
group.enzyme-opt-main.isSemVer=true
group.enzyme-opt-main.baseName=enzyme-opt (main)

compiler.enzyme-opt16-main.exe=/opt/compiler-explorer/main/enzyme-opttrunk
compiler.enzyme-opt16-main.semver=trunk
compiler.enzyme-opt16-main.options=--enzyme
compiler.enzyme-opt16-main.name=enzyme-opt trunk (4658ed0)
